databases:
  - name: postgres
    ipAllowList: []
    databaseName: budget_app_production_7e2y
    user: budget_app

services:
  - type: web
    name: my_app_render
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false